# This is a basic workflow to help you get started with Actions

name: Build Check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - name: Install yarn
        run: |
          npm install yarn -g

      - name: Check out CSKB_Hosting
        uses: actions/checkout@v4.1.1
        with:
          repository: 'Corona-Studio/CSKB_Hosting'
          path: 'CSKB_Hosting'

      - name: Remove cloned docs
        run: |
          rm -rf CSKB_Hosting/docs

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4.1.1
        with:
          path: 'CSKB_Hosting/docs'

      - name: Install Deps
        run: |
          cd CSKB_Hosting
          yarn install

      - name: Build
        run: |
          cd CSKB_Hosting
          yarn run docs:build
